In [1]:
from google.colab import drive
drive.mount("/content/MyDrive/")

Mounted at /content/MyDrive/

In [2]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [3]:
filename = '/content/MyDrive/MyDrive/codestates/cp2/2019-Oct.csv'
df = pd.read_csv(filename)
df.head()

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
0,2019-10-01 00:00:00 UTC,view,44600062,2103807459595387724,NaN,shiseido,35.79,541312140,72d76fde-8bb3-4e00-8c23-a032dfed738c
1,2019-10-01 00:00:00 UTC,view,3900821,2053013552326770905,appliances.environment.water_heater,aqua,33.20,554748717,9333dfbd-b87a-4708-9857-6336556b0fcc
2,2019-10-01 00:00:01 UTC,view,17200506,2053013559792632471,furniture.living_room.sofa,NaN,543.10,519107250,566511c2-e2e3-422b-b695-cf8e6e792ca8
3,2019-10-01 00:00:01 UTC,view,1307067,2053013558920217191,computers.notebook,lenovo,251.74,550050854,7c90fc70-0e80-4590-96f3-13c02c18c713
4,2019-10-01 00:00:04 UTC,view,1004237,2053013555631882655,electronics.smartphone,apple,1081.98,535871217,c6bd7419-2748-4c56-95b4-8cec9ff8b80d

In [ ]:
df.shape

(42448764, 9)

In [ ]:
df['event_type'].unique()

array(['view', 'purchase', 'cart'], dtype=object)

In [ ]:
df['user_id'].value_counts()

512475445    7436
512365995    4013
526731152    2912
512505687    2894
513021392    2862
             ...
556920045       1
521755468       1
515083572       1
549391147       1
544578298       1
Name: user_id, Length: 3022290, dtype: int64

In [ ]:
condition = df.event_type == 'purchase' # 구매 타입 데이터프레임
df_pca = df[condition]
df_pca.head()

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
162,2019-10-01 00:02:14 UTC,purchase,1004856,2053013555631882655,electronics.smartphone,samsung,130.76,543272936,8187d148-3c41-46d4-b0c0-9c08cd9dc564
308,2019-10-01 00:04:37 UTC,purchase,1002532,2053013555631882655,electronics.smartphone,apple,642.69,551377651,3c80f0d6-e9ec-4181-8c5c-837a30be2d68
379,2019-10-01 00:06:02 UTC,purchase,5100816,2053013553375346967,NaN,xiaomi,29.51,514591159,0e5dfc4b-2a55-43e6-8c05-97e1f07fbb56
442,2019-10-01 00:07:07 UTC,purchase,13800054,2053013557418656265,furniture.bathroom.toilet,santeri,54.42,555332717,1dea3ee2-2ded-42e8-8e7a-4e2ad6ae942f
574,2019-10-01 00:09:26 UTC,purchase,4804055,2053013554658804075,electronics.audio.headphone,apple,189.91,524601178,2af9b570-0942-4dcd-8f25-4d84fba82553

In [ ]:
a = df_pca.loc[162:574,['user_id','event_type','price']]
a

       user_id event_type   price
162  543272936   purchase  130.76
308  551377651   purchase  642.69
379  514591159   purchase   29.51
442  555332717   purchase   54.42
574  524601178   purchase  189.91

In [ ]:
df_pca['user_id'].count

<bound method Series.count of 162         543272936
308         551377651
379         514591159
442         555332717
574         524601178
              ...
42448148    516604399
42448173    514622109
42448271    512717356
42448362    533892594
42448657    544501248
Name: user_id, Length: 742849, dtype: int64>

In [ ]:
df_pca[df_pca['user_id'] == 524601178].count()

event_time       1
event_type       1
product_id       1
category_id      1
category_code    1
brand            1
price            1
user_id          1
user_session     1
dtype: int64

In [ ]:
df_pca.loc[574:574,:]

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
574,2019-10-01 00:09:26 UTC,purchase,4804055,2053013554658804075,electronics.audio.headphone,apple,189.91,524601178,2af9b570-0942-4dcd-8f25-4d84fba82553

In [ ]:
b = df_pca.loc[[162,308,379,442,574],'event_time']
b

162    2019-10-01 00:02:14 UTC
308    2019-10-01 00:04:37 UTC
379    2019-10-01 00:06:02 UTC
442    2019-10-01 00:07:07 UTC
574    2019-10-01 00:09:26 UTC
Name: event_time, dtype: object

In [ ]:
a['frequency'] = [34,15,1,5,1]

In [ ]:
a['recency'] = b
a

       user_id event_type   price  frequency                  recency
162  543272936   purchase  130.76         34  2019-10-01 00:02:14 UTC
308  551377651   purchase  642.69         15  2019-10-01 00:04:37 UTC
379  514591159   purchase   29.51          1  2019-10-01 00:06:02 UTC
442  555332717   purchase   54.42          5  2019-10-01 00:07:07 UTC
574  524601178   purchase  189.91          1  2019-10-01 00:09:26 UTC

In [ ]:
df_pca[df_pca['user_id'] == 543272936]['price'].sum()
df_pca[df_pca['user_id'] == 551377651]['price'].sum()
df_pca[df_pca['user_id'] == 514591159]['price'].sum()
df_pca[df_pca['user_id'] == 555332717]['price'].sum()
df_pca[df_pca['user_id'] == 524601178]['price'].sum()

189.91

In [ ]:
a['monetary'] = [4432.08, 4883.16, 29.51, 244.75, 189.91]

In [ ]:
a

,user_id,event_type,price,frequency,recency,monetary
162,543272936,purchase,130.76,34,2019-10-01 00:02:14 UTC,4432.08
308,551377651,purchase,642.69,15,2019-10-01 00:04:37 UTC,4883.16
379,514591159,purchase,29.51,1,2019-10-01 00:06:02 UTC,29.51
442,555332717,purchase,54.42,5,2019-10-01 00:07:07 UTC,244.75
574,524601178,purchase,189.91,1,2019-10-01 00:09:26 UTC,189.91

In [ ]:
df[event_type].count()

NameError: ignored

In [ ]:
df_pca.shape # 구매 데이터프레임 행렬 개수

(742849, 9)

In [ ]:
df_view = df[df.event_type == 'view'] # 뷰 타입 데이터프레임
df_view.head()

,event_time,event_type,product_id,category_id,category_code,brand,price,user_id,user_session
0,2019-10-01 00:00:00 UTC,view,44600062,2103807459595387724,NaN,shiseido,35.79,541312140,72d76fde-8bb3-4e00-8c23-a032dfed738c
1,2019-10-01 00:00:00 UTC,view,3900821,2053013552326770905,appliances.environment.water_heater,aqua,33.20,554748717,9333dfbd-b87a-4708-9857-6336556b0fcc
2,2019-10-01 00:00:01 UTC,view,17200506,2053013559792632471,furniture.living_room.sofa,NaN,543.10,519107250,566511c2-e2e3-422b-b695-cf8e6e792ca8
3,2019-10-01 00:00:01 UTC,view,1307067,2053013558920217191,computers.notebook,lenovo,251.74,550050854,7c90fc70-0e80-4590-96f3-13c02c18c713
4,2019-10-01 00:00:04 UTC,view,1004237,2053013555631882655,electronics.smartphone,apple,1081.98,535871217,c6bd7419-2748-4c56-95b4-8cec9ff8b80d

In [ ]:
list_pca_user = df_pca['user_id'].unique()
list_pca_user
list_price = []
for a in range(0,100001) :
  list_price.append(df_pca[df_pca['user_id'] == list_pca_user[a]]['price'].sum())
list_price[2]

KeyboardInterrupt: ignored

In [ ]:
print(df_pca.loc[df_pca['user_id'] == 551377651,'price'].sum())

4833.169999999999

In [ ]:
df_pca[df_pca['user_id'] == 551377651]['price'].sum()

4833.169999999999

In [ ]:
a = df_pca['user_id'].unique()
df_pca[df_pca['user_id'] == a[0]]['price'].sum()

4432.08

In [ ]:
list_pca_user = df_pca['user_id'].unique()
list_pca_user

array([543272936, 551377651, 514591159, ..., 514905226, 544501248,
       516662286])

In [ ]:
len(list_pca_user)

347118